meta:
  purpose : "cyber_for_0th_user_in_subset_from_300_to_349" 
  save_dir : "./data/results/arxiv_prep/cyber/"
  
data :
  cyber:
    path_to_human_process_start_data :  "/cluster/tufts/hugheslab/mwojno01/data/human_process_starts.csv"  # 1.5 GB
    subset_initial_user_idx_when_sorting_most_to_fewest_events : 300 # has 159 events 
    subset_number_of_users : 50 
    user_idx_relative_to_subset : 0 # is this truly a human user? we get 100% accuracy and the domain has C, not `DOM1`. 
    window_size : 5 
    temperature : 60  # one minute
    include_intercept : True 
    pct_training : 0.8  


holdout_performance:
  advi:
    n_iterations : 20
    seed : 0 
    lrs :
      - 0.001 
      - 0.01 
      - 0.1 
    link : 8 # SOFTMAX 

  cavi_probit:
    n_iterations:  1000

  cavi_logit: 
    n_iterations: 10 

  nuts : 
    n_warmup : 30
    n_mcmc_samples : 90
    stride_for_evaluating_holdout_performance: 1
    link: 8 # SOFTMAX 
    seed : 0 
  
  pga_softmax_gibbs:
    n_samples: 100
    pct_burn_in: 0.0
    stride_for_evaluating_holdout_performance: 1

plot:
  min_pct_iterates_with_non_nan_metrics_in_order_to_plot_curve : 0.5 
  min_log_likelihood_for_y_axis : "random guessing"