meta:
  purpose : "detergent" 
  save_dir : "./data/results/arxiv_prep/detergent/"
  
data :
  generic_real:
    dataset : 1 # DETERGENT
    standardize_design_matrix : True  
    pct_training : 0.8 
    seed : 0

holdout_performance:
  advi:
    n_iterations : 18000
    seed : 0 
    lrs :
      - 0.01 
      - 0.1 
      - 1 
    link2 : 2 # SOFTMAX 

  cavi_probit:
    n_iterations: 20000

  cavi_logit:
      n_iterations: 800

  nuts : 
    n_warmup : 20
    n_mcmc_samples : 70
    stride_for_evaluating_holdout_performance: 1
    categorical_model_type: 7 # SOFTMAX 
    seed : 0 
  
  pga_softmax_gibbs:
    n_samples: 9000
    pct_burn_in: 0.0
    stride_for_evaluating_holdout_performance: 1

plot:
  min_pct_iterates_with_non_nan_metrics_in_order_to_plot_curve : 0.5 
  min_log_likelihood_for_y_axis : "random guessing"
