meta:
  purpose : "glass" 
  save_dir : "./data/results/arxiv_prep/glass/"
  
data :
  generic_real:
    dataset : 3 # GLASS  
    standardize_design_matrix : True  
    pct_training : 0.9
    seed : 0

holdout_performance:
  advi:
    n_iterations : 10000
    seed : 0 
    lrs :
      - 0.01 
      - 0.1 
      - 1 
    link : 8 # SOFTMAX 

  cavi_probit:
    n_iterations: 10000

  cavi_logit:
      n_iterations: 500

  nuts : 
    n_warmup : 200
    n_mcmc_samples : 1000
    stride_for_evaluating_holdout_performance: 1
    link: 7 # SOFTMAX 
    seed : 0 
  
  pga_softmax_gibbs:
    n_samples: 9000
    pct_burn_in: 0.0
    stride_for_evaluating_holdout_performance: 1

plot:
  min_pct_iterates_with_non_nan_metrics_in_order_to_plot_curve : 0.5 
  min_log_likelihood_for_y_axis : "random guessing"
