meta:
  purpose : "medium_sims" 
  save_dir : "./data/results/arxiv_prep/medium_sims/"

data :
  sim:
    n_categories : 100
    n_features : 200
    n_samples : 20000 
    seed : 0 
    include_intercept : True  
    link : 1 # MULTI_LOGIT 
    scale_for_predictive_categories : 2.0
    pct_training : 0.8 

holdout_performance:
  advi:
    n_iterations : 720
    seed : 0 
    lrs :
      - 0.001 
      - 0.01 
      - 0.1
    link : 8 # SOFTMAX 

  cavi_probit:
    n_iterations: 7200

  cavi_logit:
    n_iterations: 10

  nuts : 
    n_warmup : 10
    n_mcmc_samples : 50
    stride_for_evaluating_holdout_performance: 1
    link: 7 # SOFTMAX 
    seed : 0 

  pga_softmax_gibbs:
    n_samples: 240
    pct_burn_in: 0.0
    stride_for_evaluating_holdout_performance: 1

plot:
  min_pct_iterates_with_non_nan_metrics_in_order_to_plot_curve : 0.5 
  min_log_likelihood_for_y_axis : -10.0 

